// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreetwearStore.Data;

namespace StreetwearStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201020202351_AddedListingImageEntity")]
    partial class AddedListingImageEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8787),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8857),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8860),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Air Jordan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8862),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alexander McQueen"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8864),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Supreme"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8866),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dior"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8868),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Off-White"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8870),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yeezy"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8872),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 463, DateTimeKind.Utc).AddTicks(8873),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Palm Angels"
                        });
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayCols")
                        .HasColumnType("int");

                    b.Property<int>("DisplayPositionIndex")
                        .HasColumnType("int");

                    b.Property<int>("DisplayRows")
                        .HasColumnType("int");

                    b.Property<bool>("HomeDisplay")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Colorway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.ListingImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.ListingsCollections", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("ListingsCollections");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CM")
                        .HasColumnType("float");

                    b.Property<int>("ClothSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("EU")
                        .HasColumnType("float");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("Inches")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("UK")
                        .HasColumnType("float");

                    b.Property<double>("US")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 461, DateTimeKind.Utc).AddTicks(9628),
                            EU = 38.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 5.5,
                            US = 6.0
                        },
                        new
                        {
                            Id = 2,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(358),
                            EU = 39.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 6.0,
                            US = 6.5
                        },
                        new
                        {
                            Id = 3,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(373),
                            EU = 40.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 6.5,
                            US = 7.5
                        },
                        new
                        {
                            Id = 4,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(375),
                            EU = 41.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 7.0,
                            US = 8.0
                        },
                        new
                        {
                            Id = 5,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(376),
                            EU = 42.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 7.5,
                            US = 8.5
                        },
                        new
                        {
                            Id = 6,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(378),
                            EU = 42.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 8.0,
                            US = 9.0
                        },
                        new
                        {
                            Id = 7,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(379),
                            EU = 43.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 8.5,
                            US = 9.5
                        },
                        new
                        {
                            Id = 8,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(381),
                            EU = 44.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 9.0,
                            US = 10.0
                        },
                        new
                        {
                            Id = 9,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(382),
                            EU = 44.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 9.5,
                            US = 10.5
                        },
                        new
                        {
                            Id = 10,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(383),
                            EU = 45.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 10.0,
                            US = 11.0
                        },
                        new
                        {
                            Id = 11,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(385),
                            EU = 45.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 10.5,
                            US = 11.5
                        },
                        new
                        {
                            Id = 12,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(387),
                            EU = 46.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 11.0,
                            US = 12.0
                        },
                        new
                        {
                            Id = 13,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(388),
                            EU = 47.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 11.5,
                            US = 12.5
                        },
                        new
                        {
                            Id = 14,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(389),
                            EU = 47.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 12.0,
                            US = 13.0
                        },
                        new
                        {
                            Id = 15,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(391),
                            EU = 48.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 12.5,
                            US = 13.5
                        },
                        new
                        {
                            Id = 16,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(392),
                            EU = 48.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 13.0,
                            US = 14.0
                        },
                        new
                        {
                            Id = 17,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(394),
                            EU = 49.0,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 13.5,
                            US = 14.5
                        },
                        new
                        {
                            Id = 18,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(395),
                            EU = 49.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 14.0,
                            US = 15.0
                        },
                        new
                        {
                            Id = 19,
                            CM = 0.0,
                            ClothSize = 0,
                            CreatedOn = new DateTime(2020, 10, 20, 20, 23, 50, 462, DateTimeKind.Utc).AddTicks(397),
                            EU = 50.5,
                            Gender = 0,
                            Inches = 0.0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UK = 15.0,
                            US = 16.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StreetwearStore.Data.Entities.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StreetwearStore.Data.Entities.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreetwearStore.Data.Entities.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StreetwearStore.Data.Entities.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.Listing", b =>
                {
                    b.HasOne("StreetwearStore.Data.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreetwearStore.Data.Entities.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.ListingImage", b =>
                {
                    b.HasOne("StreetwearStore.Data.Entities.Listing", "Listing")
                        .WithMany("ListingImages")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreetwearStore.Data.Entities.ListingsCollections", b =>
                {
                    b.HasOne("StreetwearStore.Data.Entities.Collection", "Collection")
                        .WithMany("CollectionProducts")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreetwearStore.Data.Entities.Listing", "Product")
                        .WithMany("ProductCollections")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
